# Generated by Django 3.0.2 on 2020-02-12 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
# Generated by Django 3.0.3 on 2020-02-19 11:16


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField(blank=True, max_length=8192)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
