# Generated by Django 3.0.2 on 2020-02-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0006_emner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emner',
            new_name='Emne',
        ),
    ]
