# Generated by Django 3.0.2 on 2020-02-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0007_auto_20200226_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='forumApp.Emne'),
        ),
    ]
