# Generated by Django 3.0.2 on 2020-02-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0008_post_emne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='emne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='forumApp.Emne'),
        ),
    ]
