# Generated by Django 3.0.4 on 2020-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0010_auto_20200316_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='userName',
            field=models.TextField(blank=True, max_length=32),
        ),
    ]
