# Generated by Django 3.0.4 on 2020-03-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0011_reportpost_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpost',
            name='userName',
        ),
        migrations.AddField(
            model_name='reportpost',
            name='title',
            field=models.CharField(default='ddd', max_length=120),
            preserve_default=False,
        ),
    ]
