# Generated by Django 3.0.4 on 2020-03-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0012_auto_20200316_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpost',
            name='title',
        ),
    ]
