# Generated by Django 3.0.4 on 2020-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0013_remove_reportpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='post_link',
            field=models.TextField(blank=True, max_length=8192),
        ),
    ]
