# Generated by Django 3.0.4 on 2020-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0018_auto_20200313_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
