# Generated by Django 3.0.4 on 2020-03-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0016_auto_20200316_1450'),
        ('forumApp', '0021_auto_20200314_1419'),
    ]

    operations = [
    ]
