# Generated by Django 3.0.4 on 2020-03-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0017_post_likes'),
        ('forumApp', '0022_merge_20200316_2030'),
    ]

    operations = [
    ]
