# Generated by Django 3.0.4 on 2020-03-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0023_merge_20200317_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
